### ISSUE TITLE
How to retrieve entire JSON string as an output in aws:executeAwsApi call

### ISSUE THREAD

**Issue by Pankajc123** [awslabs/aws-systems-manager#39]
Below is my automation document.
```
schemaVersion: '0.3'
assumeRole: 'arn:aws:iam::254163459979:role/EsriArcGISEnterprise'
mainSteps:
  - name: RetrieveJSON
    action: 'aws:executeAwsApi'
    inputs:
      Service: cloudformation
      Api: describe-stacks
      StackName: NotebookUpgTest
    outputs:
      - Name: JSONString
        Type: StringMap
        Selector: $.Stacks

```
In above automation document, how can I retrieve entire output (which is in JSON format) as "String" type instead of "StringMap".

Any help will be much appreciated.

Thanks.
